name: Publish to PyPI

# Runs only when code is merged
on: push

jobs:
  deploy:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    
    # This makes sure that only a single job of this workflow runs at a time
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      
    steps:
      - uses: actions/checkout@v2

      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user

      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .

      # Only runs if the commit is tagged
      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}